import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "PinkBlue Dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            <main className="w-full h-screen ">
              <Navbar />
              <SidebarTrigger />
              <div className="container mx-auto p-4 ">
                {children}
              </div>
            </main>
            <Toaster />
          </ThemeProvider>
        </SidebarProvider>

      </body>
    </html>
  );
}
